export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const GET_CRED_FILES_LIST_START = 'GET_CRED_FILES_LIST_START';
export const GET_CRED_FILES_LIST_SUCCESS = 'GET_CRED_FILES_LIST_SUCCESS';
export const GET_CRED_FILES_LIST_FAIL = 'GET_CRED_FILES_LIST_FAIL';
export const NET_CHECK_START = 'NET_CHECK_START';
export const NET_CHECK_SUCCESS = 'NET_CHECK_SUCCESS';
export const NET_CHECK_FAIL = 'NET_CHECK_FAIL';
// export const BLOCKCHAIN_CHECK_START = 'BLOCKCHAIN_CHECK_START';
// export const BLOCKCHAIN_CHECK_SUCCESS = 'BLOCKCHAIN_CHECK_SUCCESS';
// export const BLOCKCHAIN_CHECK_FAIL = 'BLOCKCHAIN_CHECK_FAIL';
